### PR TITLE
Coreforge's AMD Radeon driver work on 6.6.y Linux branch

### PR DESCRIPTION
**Pull request by geerlingguy**
Using this over https://github.com/geerlingguy/linux/pull/7 - see https://github.com/geerlingguy/raspberry-pi-pcie-devices/issues/564

Source for commits: https://github.com/Coreforge/linux/tree/rpi-6.6.y-gpu

### CODE REVIEW

**Review by rithvikrajraapeti — COMMENTED** [review]
LGTM

**Comment by jordan4ibanez** [comment]
Hello. I tried to compile this branch on ubuntu 24.10 raspberry pi 5 and I keep getting
```
 CALL    scripts/checksyscalls.sh
  UPD     include/generated/utsversion.h
  CC      init/version-timestamp.o
  LD      .tmp_vmlinux.kallsyms1
ld: Unexpected GOT/PLT entries detected!
ld: Unexpected run-time procedure linkages detected!
ld: arch/arm64/mm/fault.o: in function `do_alignment_fault':
/home/jordan/Desktop/linux/arch/arm64/mm/fault.c:729:(.text+0xa68): undefined reference to `do_alignment_fixup'
make[2]: *** [scripts/Makefile.vmlinux:37: vmlinux] Error 1
make[1]: *** [/home/jordan/Desktop/linux/Makefile:1164: vmlinux] Error 2
make[1]: *** Waiting for unfinished jobs....
```

I am not sure where this function comes from or I could probably patch this in. 

I almost forgot to add the obligatory image of the "Mac Pi Pro A1186"
mac_pi_pro

**Comment by jordan4ibanez** [comment]
Status update on that, I'm getting the same issue on rasberry pi os 64 bit 

image


```
  CALL    scripts/checksyscalls.sh
  UPD     include/generated/utsversion.h
  CC      init/version-timestamp.o
  LD      .tmp_vmlinux.kallsyms1
ld: Unexpected GOT/PLT entries detected!
ld: Unexpected run-time procedure linkages detected!
ld: arch/arm64/mm/fault.o: in function `do_alignment_fault':
fault.c:(.text+0x978): undefined reference to `do_alignment_fixup'
make[2]: *** [scripts/Makefile.vmlinux:37: vmlinux] Error 1
make[1]: *** [/home/jordan/Desktop/linux/Makefile:1164: vmlinux] Error 2
make[1]: *** Waiting for unfinished jobs....
^Cmake[1]: *** [/home/jordan/Desktop/linux/Makefile:1854: modules] Interrupt
make: *** [Makefile:234: __sub-make] Interrupt
```

**Comment by geerlingguy** [comment]
@jordan4ibanez - The latest steps to get everything working are in https://github.com/geerlingguy/raspberry-pi-pcie-devices/issues/680 now — I haven't kept this branch up to date, though it could still work, I just haven't re-tested in a couple months. The other branch has all the latest work.

**Comment by jordan4ibanez** [comment]
Thank you

**Comment by nicholasaiello** [comment]
i resolved the latest conflicts and pushed a branch that can be used for patching or cloning: https://github.com/nicholasaiello/linux/pull/1

the recent @Coreforge patches work great w/ my VisionTek AMD Radeon HD 7750, including w/ Vulkan + Llama.cpp — just follow the steps that @geerlingguy has shared.

Screen Shot 2024-12-17 at 9 33 41 AM
Screen Shot 2024-12-15 at 2 02 46 AM

i updated the branch w/ the latest changes this AM, as i'm doing a clean install to re-test the VisionTek card, and then swap it out for a Radeon RX 7900 XT (hopefully later tonight)

**Comment by geerlingguy** [comment]
Note, this needs a rebase on current upstream rpi-6.6.y to support the new NUMA emulation / SDRAM tweaks on the Pi 5... haven't done that yet but may soon (I have it local but have a very messed up git checkout there lol).

**Comment by Coreforge** [comment]
I rebased my branch

**Comment by geerlingguy** [comment]
Superceded by https://github.com/geerlingguy/linux/pull/10
